#!/bin/bash
TARGET="/home/$USER_NAME/$PROJECT_NAME"
REPO="/home/$USER_NAME/$PROJECT_NAME.git"
TEMP="/home/$USER_NAME/tmp"

GIT_DIR="/home/$USER_NAME/$PROJECT_NAME.git"
BRANCH=master
LOGFILE="/home/$USER_NAME/$PROJECT_NAME-logs/deploy.log"

print_double() {
    echo -e $1;
    echo -e $1 >> $LOGFILE
}

while read oldrev newrev ref
do
  print_double "Ref $ref received. Deploying ${BRANCH} branch to production..."
  print_double "===== starting deploy $(date) ====="
  print_double "Deploying commit $(git rev-parse --short HEAD) from branch: $BRANCH"

  print_double "Stopping Services"
  sudo systemctl stop django-daphne # celery celerybeat

  # backup database
  # print_double "Backing up database to deploy-$(date).json"
  # cd /home/$USER_NAME/$PROJECT_NAME >> $LOGFILE
  # pg_dump -U jaduser -W -w -F c jad > /home/$USER_NAME/database-backups/deploy-$(date).zip

  cd /home/$USER_NAME/

  # Save untracked files
  cp $TARGET/$PROJECT_NAME/production.py /home/$USER_NAME

  # Update files
  print_double "Updating files"
  mkdir -p $TEMP
  git --work-tree=$TEMP --git-dir=$GIT_DIR checkout -f $BRANCH >> $LOGFILE

  rm -rf $TARGET
  mv $TEMP $TARGET
  
  # Restore untracked files
  mv /home/$USER_NAME/production.py $TARGET/$PROJECT_NAME/
 
  cd /home/$USER_NAME/$PROJECT_NAME >> $LOGFILE

  if [ $USE_NODE = "y" ]
  then
    print_double "\nrunning npm install"
    npm install
    print_double "\nrunning npm build"
    npm run build
  fi
  
  # source /home/$USER_NAME/venv/bin/activate
  print_double "\nRunning pipenv install"
  pipenv install >> $LOGFILE
  print_double "\nRunning manage.py migrate"
  pipenv run env DJANGO_SECRET_KEY=none DJANGO_ALLOWED_HOSTS=127.0.0.1 ./manage.py migrate >> $LOGFILE
  print_double "\nRunning manage.py collectstatic"
  pipenv run env DJANGO_SECRET_KEY=none DJANGO_ALLOWED_HOSTS=127.0.0.1 ./manage.py collectstatic --noinput >> $LOGFILE

  print_double "\nRestarting services"
  sudo systemctl restart django-daphne celery celerybeat

  echo "Deployment complete, logs can be found at " $LOGFILE
  print_double "Deployment complete"
done
